/** Display names for Köppen-Geiger climate codes (the dataset uses Beck et
 *  al. (2023)'s 1 km maps - see pipeline/koppenMap.ts). */

export const KOPPEN_LABELS: Record<string, string> = {
  Af: "Tropical rainforest",
  Am: "Tropical monsoon",
  Aw: "Tropical savanna",
  As: "Tropical savanna (dry summer)",
  BWh: "Hot desert",
  BWk: "Cold desert",
  BSh: "Hot semi-arid",
  BSk: "Cold semi-arid",
  Csa: "Mediterranean (hot summer)",
  Csb: "Mediterranean (warm summer)",
  Csc: "Mediterranean (cold summer)",
  Cwa: "Humid subtropical (dry winter)",
  Cwb: "Subtropical highland (dry winter)",
  Cwc: "Subtropical highland (dry winter, cold)",
  Cfa: "Humid subtropical",
  Cfb: "Temperate oceanic",
  Cfc: "Subpolar oceanic",
  Dsa: "Hot-summer humid continental (dry summer)",
  Dsb: "Warm-summer humid continental (dry summer)",
  Dsc: "Subarctic (dry summer)",
  Dsd: "Extreme subarctic (dry summer)",
  Dwa: "Hot-summer humid continental (dry winter)",
  Dwb: "Warm-summer humid continental (dry winter)",
  Dwc: "Subarctic (dry winter)",
  Dwd: "Extreme subarctic (dry winter)",
  Dfa: "Hot-summer humid continental",
  Dfb: "Warm-summer humid continental",
  Dfc: "Subarctic",
  Dfd: "Extreme subarctic",
  ET: "Tundra",
  EF: "Ice cap",
};
